
---
apiVersion: v1
data:
    vcap-properties.yaml: dmNhcC5hcHBsaWNhdGlvbi5hcHBsaWNhdGlvbl91cmlzOiBlbnRlcnByaXNlLWFwcC01MjUyMTA4Mzktb3JkZXJzLjIwLjIzMS4xMjEuMTg0Lm5pcC5pbwp2Y2FwLmFwcGxpY2F0aW9uLmFwcGxpY2F0aW9uX3VyaXNbMF06IGVudGVycHJpc2UtYXBwLTUyNTIxMDgzOS1vcmRlcnMuMjAuMjMxLjEyMS4xODQubmlwLmlvCnZjYXAuYXBwbGljYXRpb24uY2ZfYXBpOiBodHRwczovL2FwaS4yMC4yMzEuMTIxLjE4NC5uaXAuaW8KdmNhcC5hcHBsaWNhdGlvbi5uYW1lOiBvcmRlcnMKdmNhcC5hcHBsaWNhdGlvbi52ZXJzaW9uOiA3ODg0YTEyMC0wNDBhLTQ0NGMtYmFmMi1iODhkNTg4OGQ3MjcKdmNhcC5hcHBsaWNhdGlvbi51c2VyczogCnZjYXAuYXBwbGljYXRpb24uYXBwbGljYXRpb25faWQ6IDE3MmQ2MGU1LWZhNDEtNDU1YS1iN2QzLTBhOTBlN2E4YTQzZAp2Y2FwLmFwcGxpY2F0aW9uLmFwcGxpY2F0aW9uX25hbWU6IG9yZGVycwp2Y2FwLmFwcGxpY2F0aW9uLmFwcGxpY2F0aW9uX3ZlcnNpb246IDc4ODRhMTIwLTA0MGEtNDQ0Yy1iYWYyLWI4OGQ1ODg4ZDcyNwp2Y2FwLmFwcGxpY2F0aW9uLmxpbWl0cy5tZW06IDEwMjQKdmNhcC5hcHBsaWNhdGlvbi5saW1pdHMuZGlzazogMTAyNAp2Y2FwLmFwcGxpY2F0aW9uLmxpbWl0cy5mZHM6IDE2Mzg0CnZjYXAuYXBwbGljYXRpb24uc3BhY2VfaWQ6IDMwMmZmZTBjLTM4M2QtNDRjYS04NzJiLWFmNzdiYzU5ZjYzZgp2Y2FwLmFwcGxpY2F0aW9uLnNwYWNlX25hbWU6IGVudGVycHJpc2UKdmNhcC5hcHBsaWNhdGlvbi51cmlzOiBlbnRlcnByaXNlLWFwcC01MjUyMTA4Mzktb3JkZXJzLjIwLjIzMS4xMjEuMTg0Lm5pcC5pbwp2Y2FwLmFwcGxpY2F0aW9uLnVyaXNbMF06IGVudGVycHJpc2UtYXBwLTUyNTIxMDgzOS1vcmRlcnMuMjAuMjMxLjEyMS4xODQubmlwLmlv
kind: Secret
metadata:
    creationTimestamp: null
    name: orders-vcapasspringbootproperties
type: Opaque

...
