apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  creationTimestamp: null
  name: target-enterprise-app-deploy
  namespace: openshift-gitops
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: demo
  project: default
  source:
    path: deploy/yamls
    repoURL: https://github.com/Jobinl400EY/pcf-demo
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
status:
  health: {}
  summary: {}
  sync:
    comparedTo:
      destination: {}
      source:
        repoURL: ""
    status: ""
